<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <!-- Handler để internal; chỉ mở cho dự án test đơn vị -->
    <InternalsVisibleTo Include="SOE.Identity.UnitTests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\SOE.BuildingBlocks.Application\SOE.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\SOE.Contracts\SOE.Contracts.csproj" />
    <ProjectReference Include="..\SOE.Identity.Domain\SOE.Identity.Domain.csproj" />
  </ItemGroup>

</Project>
