package com.soe.service;

import jakarta.mail.MessagingException;
import jakarta.mail.internet.MimeMessage;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

@Service
@RequiredArgsConstructor
@Slf4j
public class OutlookAlertService {

    private final JavaMailSender mailSender;

    @Value("${smartops.alert.recipient.email}")
    private String recipientEmail;

    public void sendIncidentReport(String nodeName, String issue, String resolution) {
        try {
            MimeMessage message = mailSender.createMimeMessage();
            MimeMessageHelper helper = new MimeMessageHelper(message, true, "UTF-8");

            String timeStr = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));

            String htmlContent = buildHtmlContent(nodeName, issue, resolution, timeStr);

            helper.setFrom(recipientEmail);
            // Defaulting to send to the same email for notification purposes.
            // In a real scenario, this would be read from properties or passed as an argument.
            helper.setTo(recipientEmail); 
            helper.setSubject("[Smart Ops Engine] Incident Alert: " + nodeName);
            helper.setText(htmlContent, true);

            mailSender.send(message);
            log.info("Incident report email sent successfully for node: {}", nodeName);

        } catch (MessagingException e) {
            log.error("Failed to send incident report email for node: {}", nodeName, e);
        }
    }

    private String buildHtmlContent(String nodeName, String issue, String resolution, String timeStr) {
        return "<html>" +
                "<head>" +
                "<style>" +
                "  body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #333; }" +
                "  .container { width: 100%; max-width: 600px; margin: 20px auto; border: 1px solid #e0e0e0; border-radius: 8px; overflow: hidden; box-shadow: 0 2px 4px rgba(0,0,0,0.05); }" +
                "  .header { background-color: #d32f2f; color: #ffffff; padding: 15px 20px; text-align: center; border-bottom: 3px solid #b71c1c; }" +
                "  .header h2 { margin: 0; font-size: 20px; font-weight: 600; }" +
                "  .content { padding: 25px 20px; background-color: #fafafa; }" +
                "  .field { margin-bottom: 15px; padding-bottom: 15px; border-bottom: 1px solid #eeeeee; }" +
                "  .field:last-child { border-bottom: none; margin-bottom: 0; padding-bottom: 0; }" +
                "  .label { font-weight: 600; color: #555555; display: block; margin-bottom: 5px; font-size: 14px; }" +
                "  .value { font-size: 16px; color: #212121; }" +
                "  .value.error { color: #d32f2f; font-weight: bold; }" +
                "  .footer { margin-top: 20px; padding: 15px; font-size: 12px; color: #9e9e9e; text-align: center; border-top: 1px solid #e0e0e0; background-color: #ffffff; }" +
                "</style>" +
                "</head>" +
                "<body>" +
                "  <div class='container'>" +
                "    <div class='header'>" +
                "      <h2>🚨 Incident Alert Report</h2>" +
                "    </div>" +
                "    <div class='content'>" +
                "      <div class='field'>" +
                "        <span class='label'>Server Name</span>" +
                "        <span class='value'>" + nodeName + "</span>" +
                "      </div>" +
                "      <div class='field'>" +
                "        <span class='label'>Error Type</span>" +
                "        <span class='value error'>" + issue + "</span>" +
                "      </div>" +
                "      <div class='field'>" +
                "        <span class='label'>Action Taken</span>" +
                "        <span class='value'>" + resolution + "</span>" +
                "      </div>" +
                "      <div class='field'>" +
                "        <span class='label'>Time</span>" +
                "        <span class='value'>" + timeStr + "</span>" +
                "      </div>" +
                "    </div>" +
                "    <div class='footer'>" +
                "      This is an automated message generated by Smart Ops Engine.<br>Please do not reply to this email." +
                "    </div>" +
                "  </div>" +
                "</body>" +
                "</html>";
    }

    public void sendDailySummaryReport(int activeNodesCount, long openIncidentsCount) {
        try {
            MimeMessage message = mailSender.createMimeMessage();
            MimeMessageHelper helper = new MimeMessageHelper(message, true, "UTF-8");

            String timeStr = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));

            String htmlContent = "<html>" +
                    "<head>" +
                    "<style>" +
                    "  body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #333; }" +
                    "  .container { width: 100%; max-width: 600px; margin: 20px auto; border: 1px solid #e0e0e0; border-radius: 8px; overflow: hidden; box-shadow: 0 2px 4px rgba(0,0,0,0.05); }" +
                    "  .header { background-color: #1976d2; color: #ffffff; padding: 15px 20px; text-align: center; border-bottom: 3px solid #1565c0; }" +
                    "  .header h2 { margin: 0; font-size: 20px; font-weight: 600; }" +
                    "  .content { padding: 25px 20px; background-color: #fafafa; }" +
                    "  .field { margin-bottom: 15px; padding-bottom: 15px; border-bottom: 1px solid #eeeeee; }" +
                    "  .field:last-child { border-bottom: none; margin-bottom: 0; padding-bottom: 0; }" +
                    "  .label { font-weight: 600; color: #555555; display: block; margin-bottom: 5px; font-size: 14px; }" +
                    "  .value { font-size: 16px; color: #212121; }" +
                    "  .footer { margin-top: 20px; padding: 15px; font-size: 12px; color: #9e9e9e; text-align: center; border-top: 1px solid #e0e0e0; background-color: #ffffff; }" +
                    "</style>" +
                    "</head>" +
                    "<body>" +
                    "  <div class='container'>" +
                    "    <div class='header'>" +
                    "      <h2>📊 Daily Health Report Summary</h2>" +
                    "    </div>" +
                    "    <div class='content'>" +
                    "      <div class='field'>" +
                    "        <span class='label'>Thời gian báo cáo</span>" +
                    "        <span class='value'>" + timeStr + "</span>" +
                    "      </div>" +
                    "      <div class='field'>" +
                    "        <span class='label'>Số lượng Node đang hoạt động</span>" +
                    "        <span class='value'>" + activeNodesCount + "</span>" +
                    "      </div>" +
                    "      <div class='field'>" +
                    "        <span class='label'>Sự cố chưa giải quyết (OPEN)</span>" +
                    "        <span class='value' style='color: " + (openIncidentsCount > 0 ? "#d32f2f" : "#2e7d32") + "; font-weight: bold;'>" + openIncidentsCount + "</span>" +
                    "      </div>" +
                    "      <div class='field'>" +
                    "        <span class='label'>Trạng thái hệ thống</span>" +
                    "        <span class='value'>" + (openIncidentsCount > 0 ? "Cần chú ý - Có sự cố chưa xử lý." : "Hoạt động bình thường.") + "</span>" +
                    "      </div>" +
                    "    </div>" +
                    "    <div class='footer'>" +
                    "      This is an automated message generated by Smart Ops Engine.<br>Please do not reply to this email." +
                    "    </div>" +
                    "  </div>" +
                    "</body>" +
                    "</html>";

            helper.setFrom(recipientEmail);
            helper.setTo(recipientEmail);
            helper.setSubject("[Smart Ops Engine] Daily Health Report Summary");
            helper.setText(htmlContent, true);

            mailSender.send(message);
            log.info("Daily summary report email sent successfully.");

        } catch (MessagingException e) {
            log.error("Failed to send daily summary report email", e);
        }
    }
}
